on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'terraform/**'

jobs:
  kics:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RESULTS_DIR: results-dir
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create KICS Results Directory
        run: mkdir -p ${{ env.RESULTS_DIR }}

      - name: KICS Scan
        uses: Checkmarx/kics-github-action@85b2f1325cc8f0c8df31e75e6384d6694e0f1cbf
        with:
          enable_comments: true
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: ${{ env.RESULTS_DIR }}/
          output_formats: "sarif"
          config_path: terraform/kics.yml

      # Send the SARIF output to GitHub.
      - name: Populate Github Security Tab Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ env.RESULTS_DIR }}/results.sarif