on:
  push:
    paths:
      - 'serverless/mail-handler/**'
    branches:
      - main
      - staging
      - develop
jobs:
  deploy:
    name: deploy
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_TOKEN }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Branch Name From Push
        id: branch-merge
        if: github.event_name == 'push'
        run: echo "branch=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Branch Name Case Transformation
        id: branch
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ env.branch}}

      - name: Set Secret Keys
        id: set-secret-keys
        run: |
          echo "::set-output name=AWS_DEPLOY_ROLE::AWS_${{steps.branch.outputs.uppercase}}_DEPLOY_ROLE"

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_KEY_DEPLOYMENT}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_DEPLOYMENT}}
          role-to-assume: ${{secrets[steps.set-secret-keys.outputs.AWS_DEPLOY_ROLE]}}
          role-duration-seconds: 3600
          aws-region: "us-east-2"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i -g serverless
      - run: npm i -g serverless-plugin-resource-tagging
      - run: serverless --version
      - run: serverless deploy --stage ${{ steps.branch.outputs.lowercase }} --verbose
        working-directory: ./serverless/mail-handler
