on:
  pull_request:
    paths:
      - 'terraform/**'
    branches:
      - develop
      - staging
      - main
  push:
    paths:
      - 'terraform/**'
    branches:
      - develop
      - staging
      - main
jobs:
  terraform_plan:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Terraform Plan, PR Comment, Conditional Apply
        uses: zbmowrey/deploy-terraform/.github/workflows/terraform.yml@main